### ISSUE TITLE
Move to requireContext calls instead of getContext calls in fragments

### ISSUE THREAD

**Issue by patrickhammond** [atomicrobot/Carbon-Android#72]
@atoennis can explain more.

**Comment by atoennis** [comment]
This functionality was added in the `27.1.0` release.  From the release notes
> Fragments now have requireContext(), requireActivity(), requireHost(), and requireFragmentManager() methods, which return a NonNull object of the equivalent get methods or throw an IllegalStateException.

Typically in a fragment, if a null context is retrieved it's because the fragment hasn't been attached to the Activity yet.  In these scenarios, it's more than likely a timing mistake on when the context was retrieved.  In this scenario it's better for the exception to be thrown rather than do nothing in the else block of a null check.  These new calls assist in that behavior and play nicely with Kotlin (no more dealing with optional contexts, `!!`)

https://developer.android.com/topic/libraries/support-library/revisions#27-1-0

**Comment by ascheetz** [comment]
Updated when moving to Compose
