### ISSUE TITLE
Coroutines?

### ISSUE THREAD

**Issue by weverb2** [atomicrobot/Carbon-Android#86]
Should coroutines be the way going forward?  

RxJava works pretty well, what would be the criteria for replacing it?

Would they work side by side or would that be too much?

**Comment by atoennis** [comment]
One hangup I've seen with replacing it is coroutines are good for the threading aspect but not for handling streams, which Rx does both.

I haven't looked into Channels much but possibly when that's out of Experimental coroutines are then feature parity with Rx?

**Comment by weverb2** [comment]
Flow and Channel seem to be a replacement for streams.  I think a conservative approach would be coroutines to start, Rx when you need it.   You don't need Rx to make network calls, when retrofit has built in async / await support.  A lot of problems can be solved with Rx, but that doesn't mean they should be.

**Comment by atoennis** [comment]
The challenge is currently Rx is used everywhere across the interactor layer.  That includes network calls but also anything else (i.e repository).  It's also responsible for managing the streams of data (timing, mapping, etc).

Right now Rx isn't perfect due to its steep learning curve however we have used it to great effect.  If it gets replaced, it's replacement should hit at least most of the benefits that Rx provides.

**Comment by weverb2** [comment]
I think coroutines can be solve all of those issues. Mapping isn't a function of a threading library, so we can pull that out of Rx and more into a data layer. Timing and combining of data sources can all be solved without subjects and just as suspending functions. But even if you need streams, coroutines should have you covered.

**Comment by bradyjohnk** [comment]
Using corroutines and flow
